### Numpy

NumPy (Numerical Python) is the foundational package for numerical computing in Python.
It provides:
- Powerful N-dimensional array object (ndarray)
- Broadcasting functions
- Tools for integrating C/C++/Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities

To install NumPy:
```
pip install numpy
```

In [1]:
import numpy as np

### Creating NumPy Arrays

In [3]:
# From a Python list
array1 = np.array([1, 2, 3, 4])
print("1D array:", array1)

# From a list of lists
array2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", array2)

# Create arrays with default values
zeros = np.zeros((2, 3))       # 2x3 array of zeros
ones = np.ones((3, 2))         # 3x2 array of ones
full = np.full((2, 2), 7)      # 2x2 array filled with 7
identity = np.eye(3)           # 3x3 Identity matrix
print("Array of zeros:\n", zeros)
print("Identity matrix:\n", identity)

# Create sequences
arange = np.arange(0, 10, 2)   # From 0 to 10 with step 2
linspace = np.linspace(0, 1, 5) # 5 values from 0 to 1
print("arange:", arange)
print("linspace:", linspace)

1D array: [1 2 3 4]
2D array:
 [[1 2 3]
 [4 5 6]]
Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Create sequences

arange = np.arange(0, 10, 2)   # From 0 to 10 with step 2
linspace = np.linspace(0, 1, 5) # 5 values from 0 to 1
print("arange:", arange)    
print("linspace:", linspace)

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


**Linspace and arange**

- linspace
  - Purpose: Creates a specific number of evenly spaced values between a start and stop value   (both included by default).
  
   Syntax:
   ```
   np.linspace(start, stop, num=50)
   ```


- arange
  - Purpose: Creates numbers at a regular step between start and stop (stop is not included).
    
    Syntax
    ```
    np.arange(start, stop, step)
    ```

### Array Properties

In [9]:

print("Shape:", array2.shape)
print("Data type:", array2.dtype)
print("Size (number of elements):", array2.size)
print("Dimensions (ndim):", array2.ndim)

Shape: (2, 3)
Data type: int64
Size (number of elements): 6
Dimensions (ndim): 2


### Indexing and slicing

In [10]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Element at row 1, column 2:", arr[1, 2])
print("First row:", arr[0])
print("All rows, column 1:", arr[:, 1])
print("Subarray:\n", arr[0:2, 1:3])


Element at row 1, column 2: 60
First row: [10 20 30]
All rows, column 1: [20 50 80]
Subarray:
 [[20 30]
 [50 60]]


### Operations

In [ ]:
# Element-wise operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)
print("Multiplication:", a * b)
print("Exponentiation:", a ** 2)

# Matrix multiplication
A = np.array([
    [1, 2], 
    [3, 4]
])
B = np.array([[2, 0], [1, 2]])
print("Matrix product:\n", A @ B)

# Aggregations
print("Sum:", A.sum())
print("Max:", A.max())
print("Mean:", A.mean())
print("Standard Deviation:", A.std())

# Axis-specific aggregations
print("Column-wise sum:", A.sum(axis=0))
print("Row-wise mean:", A.mean(axis=1))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Exponentiation: [1 4 9]
Matrix product:
 [[ 4  4]
 [10  8]]
Sum: 10
Max: 4
Mean: 2.5
Standard Deviation: 1.118033988749895
Column-wise sum: [4 6]
Row-wise mean: [1.5 3.5]


### Reshaping and Flattening

In [13]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print("Original shape:", c.shape)

reshaped = c.reshape((3, 2))
print("Reshaped to 3x2:\n", reshaped)

flattened = c.flatten()
print("Flattened array:", flattened)



Original shape: (2, 3)
Reshaped to 3x2:
 [[1 2]
 [3 4]
 [5 6]]
Flattened array: [1 2 3 4 5 6]


### Stacking Arrays

In [16]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print("Vertical stack:\n", np.vstack((a, b)))
print("Horizontal stack:\n", np.hstack((a, a)))


Vertical stack:
 [[1 2]
 [3 4]
 [5 6]]
Horizontal stack:
 [[1 2 1 2]
 [3 4 3 4]]


### Boolean Indexing and Filtering

In [18]:
data = np.array([10, 20, 30, 40, 50])
condition = data > 30
print("Condition:", condition)
print("Filtered result:", data[condition])


Condition: [False False False  True  True]
Filtered result: [40 50]


### Random Numbers

In [19]:

rand_uniform = np.random.rand(3, 2)  # Uniform [0, 1)
rand_normal = np.random.randn(3, 2)  # Standard normal
rand_int = np.random.randint(0, 10, (2, 3))  # Random ints
print("Random uniform:\n", rand_uniform)
print("Random integers:\n", rand_int)


Random uniform:
 [[0.90992184 0.09911703]
 [0.52177422 0.29663968]
 [0.61843136 0.81180321]]
Random integers:
 [[7 1 5]
 [7 5 4]]


### Useful NumPy Functions

In [20]:
arr = np.array([3, 1, 4, 1, 5, 9, 2])
sorted_arr = np.sort(arr)
unique_vals = np.unique(arr)

print("Sorted array:", sorted_arr)
print("Unique values:", unique_vals)


Sorted array: [1 1 2 3 4 5 9]
Unique values: [1 2 3 4 5 9]


### Broadcasting
Broadcasting means NumPy automatically expands smaller arrays so they can work together with bigger arrays in operations — without you manually changing their shape.

It lets you do math on arrays of different shapes without writing loops.

In [21]:
arr = np.array([[1], [2], [3]])
vector = np.array([10, 20, 30])
print("Broadcasted addition:\n", arr + vector)


Broadcasted addition:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]
